name: Auto deploy on Dev

on:
  push:
    branches: [ "v1.0/main" ]
    
env:
  ARM_CLIENT_SECRET: ${{  secrets.ARM_CLIENT_SECRET  }}
  ARM_SUBSCRIPTION_ID: ${{  secrets.ARM_SUBSCRIPTION_ID  }}
  ARM_TENANT_ID: ${{  secrets.ARM_TENANT_ID  }}
  ARM_CLIENT_ID: ${{  secrets.ARM_CLIENT_ID  }}

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to docker registry
      env: 
        registry_token: ${{ secrets.REGISTRY_TOKEN }}
      run: docker login containerregistrypocitt.azurecr.io -u containerregistrypocitt -p $registry_token
    - name: Create env file
      working-directory: ./containerization/image-build
      env:
        MONGO_URI: ${{  secrets.MONGO_URI  }}
        HOST_URL: ${{  secrets.HOST_URL  }}
      run: |
        touch .env
        echo MONGO_URI=$MONGO_URI >> .env
        echo HOST_URL=$HOST_URL >> .env
    - name: Build docker image
      working-directory: ./containerization/image-build
      run: docker build . --tag containerregistrypocitt.azurecr.io/app-user:latest
    - name: Push images
      run: docker push containerregistrypocitt.azurecr.io/app-user:latest
  
  deploy_on_dev_env:
    needs: build_docker_image
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: configure client secret
      run: export ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET
    
    - name: configure subscription id
      run: export ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
    
    - name: configure tenant id
      run: export ARM_TENANT_ID=$ARM_TENANT_ID

    - name: configure client id
      run: export ARM_CLIENT_ID=$ARM_CLIENT_ID

    - name: Initialize Terraform
      working-directory: ./containerization/infrastructure/deploy-container
      run: terraform init

    - name: Try terraform
      env: 
        registry_token: ${{ secrets.REGISTRY_TOKEN }}
      working-directory: ./containerization/infrastructure/deploy-container
      run: terraform plan -var application_version=latest -var registry_password=$registry_token

    - name: Deployment on dev
      env: 
        registry_token: ${{ secrets.REGISTRY_TOKEN }}
      working-directory: ./containerization/infrastructure/deploy-container
      run: terraform apply -var application_version=latest  -var registry_password=$registry_token -target azurerm_container_group.container-poc-test -auto-approve